### PR TITLE
pc upload modify docs

### PR DESCRIPTION
**Pull request by ElijahAhianyo**
modified docs to reflect current changes in pynecone main. Also, added an example for extra clarity

### CODE REVIEW

**Comment by masenf** [comment]
is this superseding #54?

then `upload_code_2` doesn't quite look right... trying to append the `file.filename` to a str
https://github.com/pynecone-io/pcweb/pull/55/files#diff-a39c40b4f305b81c46aa9794954635b6b30d1cbde6d9b61811545cd444353f16R774-R775

**Comment by ElijahAhianyo** [comment]
> is this superseding #54?
> 
> then `upload_code2` doesn't quite look right... trying to append the `file.filename` to a str https://github.com/pynecone-io/pcweb/pull/55/files#diff-a39c40b4f305b81c46aa9794954635b6b30d1cbde6d9b61811545cd444353f16R774-R775

Ah, good catch! the #54 PR should definitely be merged before this one

**Review by Alek99 — APPROVED** [review]
Nice lg

**Comment by Alek99** [comment]
Ah I see @ElijahAhianyo you will probably need to rebase on main I merged in 54 getting conflicts now

**Comment by ElijahAhianyo** [comment]
> Ah I see @ElijahAhianyo you will probably need to rebase on main I merged in 54 getting conflicts now. I'll re review once rebased

Fixed this now

**Review by Alek99 — APPROVED** [review]
Awesome thanks!

**Pull request merged**
